# 2 - apiserversba services
apiVersion: v1
kind: Service
metadata:
  name: apiserversba-services
  # namespace: apiserversba
spec:
  type: ClusterIP
  ports:
    - name: services
      port: 80
      targetPort: 8080
  selector:
    app: apiserversba
    tier: services
---
# microservices components 2 - api services
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apiserversba-services
  name: apiserversba-services
  # namespace: apiserversba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserversba
      tier: services
  template:
    metadata:
      labels:
        app: apiserversba
        tier: services
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: /actuator/prometheus        
    spec:
      volumes: 
      - name: elastic-apm-agent 
        emptyDir: {}    
      initContainers: 
      - name: elastic-java-agent 
        image: docker.elastic.co/observability/apm-agent-java:1.12.0 
        volumeMounts: 
        - mountPath: /elastic/apm/agent 
          name: elastic-apm-agent 
        command: ['cp', '-v', '/usr/agent/elastic-apm-agent.jar', '/elastic/apm/agent']     
      containers:
        - image: leedockdocker/sqs3
          imagePullPolicy: Always
          name: apiserversba-services
          volumeMounts: 
          - mountPath: /elastic/apm/agent 
            name: elastic-apm-agent          
          env:
            - name: spring.application.name
              value: apiserversba-services-lee
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres:5432/smartbankapp
            - name: spring.datasource.username
              value: postgres
            - name: spring.datasource.password
              value: postgres
            - name: server.port
              value: "8080"
            - name: cloud.aws.end-point.uri
              value: "https://sqs.ap-south-1.amazonaws.com/175652158808/lee-sba"
            - name: cloud.aws.region.static
              value: "ap-south-1"  
            - name: spring.mail.host
              value: "email-smtp.ap-south-1.amazonaws.com" 
            - name: spring.mail.properties.mail.transport.protocol
              value: "smtp" 
            - name: spring.mail.properties.mail.smtp.port
              value: "587" 
            - name: spring.mail.properties.mail.smtp.auth
              value: "true" 
            - name: spring.mail.properties.mail.smtp.starttls.enable
              value: "true" 
            - name: spring.mail.properties.mail.smtp.starttls.required
              value: "true"   
            - name: ELASTIC_APM_SERVER_URL 
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ELASTIC_APM_SERVER_URL
            - name: ELASTIC_APM_APPLICATION_PACKAGES 
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ELASTIC_APM_APPLICATION_PACKAGES
            - name: ELASTIC_APM_SERVICE_NAME 
              value: "apiserversba-services-lee" 
            - name: ELASTIC_APM_ENVIRONMENT 
              value: prod
            - name: ELASTIC_APM_LOG_LEVEL 
              value: DEBUG 
            - name: JAVA_TOOL_OPTIONS 
              value: -javaagent:/elastic/apm/agent/elastic-apm-agent.jar               
            - name: management.endpoints.web.exposure.include
              value: "*"
            - name: management.server.port
              value: "8888"
            - name: management.metrics.web.server.request.autotime.enabled
              value: "true"
            - name: management.metrics.tags.application
              value: apiserversba-services-lee         
          ports:
            - containerPort: 8080
